branch-defaults:
  main:
    environment: Lab16-eb-CLI-deploy-dev
    group_suffix: null
environment-defaults:
  Lab16-eb-CLI-deploy-dev:
    branch: main
    repository: Lab16-AWS-Basic-Express
global:
  application_name: Lab16-eb-CLI-deploy
  branch: main
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: Lab16-AWS-Basic-Express
  sc: git
  workspace_type: Application
